// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package log implements a simple logging package. It defines a type, Logger,
// with methods for formatting output. It also has a predefined 'standard'
// Logger accessible through helper functions Print[f|ln], Fatal[f|ln], and
// Panic[f|ln], which are easier to use than creating a Logger manually.
// That logger writes to standard error and prints the date and time
// of each logged message.
// The Fatal functions call os.Exit(1) after writing the log message.
// The Panic functions call panic after writing the log message.
package log

import (
	"fmt"
	"io"
	"os"
	"path"
	"runtime"
	"strings"
	"sync"
	"time"

	"github.com/lircstar/nemo/sys/util"
)

// These flags define which text to prefix to each log entry generated by the Logger.
const (
	// Bits or'ed together to control what's printed. There is no control over the
	// order they appear (the order listed here) or the format they present (as
	// described in the comments).  A colon appears after these items:
	//	2009/01/23 01:23:23.123123 /a/b/c/d.go:23: message
	Ldate         = 1 << iota     // the date: 2009/01/23
	Ltime                         // the time: 01:23:23
	Lmicroseconds                 // microsecond resolution: 01:23:23.123123.  assumes Ltime.
	Llongfile                     // full file name and line number: /a/b/c/d.go:23
	Lshortfile                    // final file name element and line number: d.go:23. overrides Llongfile
	LstdFlags     = Ldate | Ltime // initial values for the standard logger

)

// A Logger represents an active logging object that generates lines of
// output to an io.Writer.  Each logging operation makes a single call to
// the Writer's Write method.  A Logger can be used simultaneously from
// multiple goroutines; it guarantees to serialize access to the Writer.
type Logger struct {
	mu          sync.Mutex // ensures atomic writes; protects the following fields
	flag        int        // properties
	buf         []byte     // for accumulating text to write
	level       Level
	panicLevel  Level
	enableColor bool
	name        string
	colorFile   *ColorFile

	fileOutput *os.File
}

// New creates a new Logger.   The out variable sets the
// destination to which log data will be written.
// The prefix appears at the beginning of each generated log line.
// The flag argument defines the logging properties.

func New(name string, colorenable bool) *Logger {
	l := &Logger{flag: LstdFlags, level: Level_Debug, name: name, panicLevel: Level_Fatal}
	if colorenable {
		l.defaultColorFile()
	}
	return l
}

// Cheap integer to fixed-width decimal ASCII.  Give a negative width to avoid zero-padding.
// Knows the buffer has capacity.
func itoa(buf *[]byte, i int, wid int) {
	var u uint = uint(i)
	if u == 0 && wid <= 1 {
		*buf = append(*buf, '0')
		return
	}

	// Assemble decimal in reverse order.
	var b [32]byte
	bp := len(b)
	for ; u > 0 || wid > 0; u /= 10 {
		bp--
		wid--
		b[bp] = byte(u%10) + '0'
	}
	*buf = append(*buf, b[bp:]...)
}

func (log *Logger) formatHeader(t time.Time, buf *[]byte, file string, line int) {

	*buf = append(*buf, ' ')

	if log.flag&(Ldate|Ltime|Lmicroseconds) != 0 {
		if log.flag&Ldate != 0 {
			year, month, day := t.Date()
			itoa(buf, year, 4)
			*buf = append(*buf, '/')
			itoa(buf, int(month), 2)
			*buf = append(*buf, '/')
			itoa(buf, day, 2)
			*buf = append(*buf, ' ')
		}
		if log.flag&(Ltime|Lmicroseconds) != 0 {
			hour, min, sec := t.Clock()
			itoa(buf, hour, 2)
			*buf = append(*buf, ':')
			itoa(buf, min, 2)
			*buf = append(*buf, ':')
			itoa(buf, sec, 2)
			if log.flag&Lmicroseconds != 0 {
				*buf = append(*buf, '.')
				itoa(buf, t.Nanosecond()/1e3, 6)
			}
			*buf = append(*buf, ' ')
		}
	}

	if log.flag&(Lshortfile|Llongfile) != 0 {
		if log.flag&Lshortfile != 0 {
			short := file
			for i := len(file) - 1; i > 0; i-- {
				if file[i] == '/' {
					short = file[i+1:]
					break
				}
			}
			file = short
		}
		*buf = append(*buf, file...)
		*buf = append(*buf, ':')
		itoa(buf, line, -1)
		*buf = append(*buf, ": "...)
	}
}

// Output writes the output for a logging event.  The string s contains
// the text to print after the prefix specified by the flags of the
// Logger.  A newline is appended if the last character of s is not
// already a newline.  Calldepth is used to recover the PC and is
// provided for generality, although at the moment on all pre-defined
// paths it will be 2.
func (log *Logger) Output(calldepth int, prefix string, text string, c Color, out io.Writer) error {
	now := time.Now() // get this early.
	var file string
	var line int
	log.mu.Lock()
	defer log.mu.Unlock()
	if log.flag&(Lshortfile|Llongfile) != 0 {
		// release lock while getting caller info - it'text expensive.
		log.mu.Unlock()
		var ok bool
		_, file, line, ok = runtime.Caller(calldepth)
		if !ok {
			file = "???"
			line = 0
		}
		log.mu.Lock()
	}
	log.buf = log.buf[:0]

	colorLog := c != NoColor

	if colorLog {
		log.buf = append(log.buf, logColorPrefix[c]...)
	}

	log.formatHeader(now, &log.buf, file, line)
	log.buf = append(log.buf, prefix...)
	log.buf = append(log.buf, ' ')
	log.buf = append(log.buf, ' ')
	log.buf = append(log.buf, text...)

	if colorLog {
		log.buf = append(log.buf, logColorSuffix...)
	}

	if len(text) > 0 && text[len(text)-1] != '\n' {
		log.buf = append(log.buf, '\n')
	}

	_, err := out.Write(log.buf)

	return err
}

func (log *Logger) Log(c Color, level Level, format string, v ...any) {

	if level < log.level {
		return
	}

	prefix := fmt.Sprintf("%s", levelString[level])

	var text string

	if format == "" {
		text = fmt.Sprintln(v...)
	} else {
		text = fmt.Sprintf(format, v...)
	}

	var out io.Writer

	if log.enableColor {

		if log.colorFile != nil && c == NoColor {
			c = log.colorFile.ColorFromText(text)
		}

		if level >= Level_Error {
			c = Red
		}
	} else {
		c = NoColor
	}

	if log.fileOutput == nil {
		out = os.Stdout
	} else {
		out = log.fileOutput
	}

	_ = log.Output(3, prefix, text, c, out)

	if int(level) >= int(log.panicLevel) {
		panic(text)
	}

}

func (log *Logger) Debugf(format string, v ...any) {
	log.Log(ColorFromLevel(Level_Debug), Level_Debug, format, v...)
}

func (log *Logger) Debug(v ...any) {
	log.Log(ColorFromLevel(Level_Debug), Level_Debug, "", v...)
}

func (log *Logger) Infof(format string, v ...any) {
	log.Log(ColorFromLevel(Level_Info), Level_Info, format, v...)
}

func (log *Logger) Info(v ...any) {
	log.Log(ColorFromLevel(Level_Info), Level_Info, "", v...)
}

func (log *Logger) Warnf(format string, v ...any) {
	log.Log(ColorFromLevel(Level_Warn), Level_Warn, format, v...)
}

func (log *Logger) Warn(v ...any) {
	log.Log(ColorFromLevel(Level_Warn), Level_Warn, "", v...)
}

func (log *Logger) Errorf(format string, v ...any) {
	log.Log(ColorFromLevel(Level_Error), Level_Error, format, v...)
}

func (log *Logger) Error(v ...any) {
	log.Log(ColorFromLevel(Level_Error), Level_Error, "", v...)
}

func (log *Logger) Fatalf(format string, v ...any) {

	log.Log(ColorFromLevel(Level_Fatal), Level_Fatal, format, v...)
}

func (log *Logger) Fatal(v ...any) {
	log.Log(ColorFromLevel(Level_Fatal), Level_Fatal, "", v...)
}

func (log *Logger) Recover() {
	if r := recover(); r != nil {
		buf := make([]byte, 4096)
		l := runtime.Stack(buf, false)
		log.Error("%v: %s", r, buf[:l])
	}
}

func (log *Logger) LogFile(filepath string) bool {
	now := time.Now()
	filename := fmt.Sprintf("%s[%d%02d%02d%02d%02d%02d].log",
		log.name,
		now.Year(),
		now.Month(),
		now.Day(),
		now.Hour(),
		now.Minute(),
		now.Second())

	filename = path.Join(filepath, filename)
	mode := os.O_RDWR | os.O_CREATE | os.O_APPEND
	file, err := os.OpenFile(filename, mode, 0666)
	if err != nil {
		return false
	}
	log.enableColor = false
	log.fileOutput = file

	return true
}
func str2loglevel(level string) Level {

	switch level {
	case "debug":
		return Level_Debug
	case "info":
		return Level_Info
	case "warn":
		return Level_Warn
	case "error":
		return Level_Error
	case "fatal":
		return Level_Fatal
	}

	return Level_Debug
}

func (log *Logger) SetLevelByString(level string) {
	log.SetLevel(str2loglevel(level))
}

func (log *Logger) SetLevel(lv Level) {
	log.level = lv
}

func (log *Logger) Level() Level {
	return log.level
}

func (log *Logger) SetPanicLevelByString(level string) {
	log.panicLevel = str2loglevel(level)
}

func str2logflag(f string) int {
	flag := LstdFlags
	flags := strings.Split(f, "|")
	for _, s := range flags {
		v := strings.ToLower(strings.Trim(s, " "))
		switch v {
		case "longfile":
			flag |= Llongfile
			break
		case "shortfile":
			flag |= Lshortfile
			break
		case "longtime":
			flag |= Lmicroseconds
			break
		}
	}
	return flag
}

func (log *Logger) SetFlags(flag int) {
	log.flag = flag
}

func (log *Logger) SetFlagsByString(f string) {
	log.flag = str2logflag(f)
}

// SetColorFile 注意, 加色只能在Goland的main方式启用, Test方式无法加色
func (log *Logger) SetColorFile(file *ColorFile) {
	log.colorFile = file
	log.colorFile.Load("color_sample.json")
	log.enableColor = true
}

func (log *Logger) IsDebugEnabled() bool {
	return log.level == Level_Debug
}

func (log *Logger) defaultColorFile() {
	log.colorFile = NewColorFile()
	log.colorFile.Load("color_sample.json")
	if log.fileOutput == nil {
		log.enableColor = true
	}
}

func (log *Logger) Close() {
	if log.fileOutput != nil {
		log.fileOutput.Close()
	}

	log.fileOutput = nil
}

// global log object.
var gLogger = New(util.GetProcessName(), true)

// It's dangerous to call the method on logging
func Export(logger *Logger) {
	if logger != nil {
		gLogger = logger
	}
}

func SetLevel(lv string) {
	gLogger.SetLevelByString(lv)
}

func SetFlags(flag string) {
	gLogger.SetFlagsByString(flag)
}

func LogFile() {
	gLogger.LogFile(util.GetProcessPath())
}

func Close() {
	gLogger.Close()
}

func Debugf(format string, v ...any) {
	gLogger.Log(ColorFromLevel(Level_Debug), Level_Debug, format, v...)
}

func Debug(v ...any) {
	gLogger.Log(ColorFromLevel(Level_Debug), Level_Debug, "", v...)
}

func Infof(format string, v ...interface{}) {
	gLogger.Log(ColorFromLevel(Level_Info), Level_Info, format, v...)
}

func Info(v ...interface{}) {
	gLogger.Log(ColorFromLevel(Level_Info), Level_Info, "", v...)
}

func Warnf(format string, v ...interface{}) {
	gLogger.Log(ColorFromLevel(Level_Warn), Level_Warn, format, v...)
}

func Warn(v ...interface{}) {
	gLogger.Log(ColorFromLevel(Level_Warn), Level_Warn, "", v...)
}

func Errorf(format string, v ...interface{}) {
	gLogger.Log(ColorFromLevel(Level_Error), Level_Error, format, v...)
}

func Error(v ...interface{}) {
	gLogger.Log(ColorFromLevel(Level_Error), Level_Error, "", v...)
}

func Fatalf(format string, v ...interface{}) {
	gLogger.Log(ColorFromLevel(Level_Fatal), Level_Fatal, format, v...)
}

func Fatal(v ...interface{}) {
	gLogger.Log(ColorFromLevel(Level_Fatal), Level_Fatal, "", v...)
}

func Recover() {
	if r := recover(); r != nil {
		buf := make([]byte, 4096)
		l := runtime.Stack(buf, false)
		gLogger.Error("%v: %s", r, buf[:l])
	}
}
